import { SliceLike, SliceZoneLike } from '@prismicio/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { FunctionComponent, useState } from 'react'
import { BottomBar } from '../components/bottombar/bottombar'
import { Playlist } from '../components/Playlist/Playlist'
import { createClient } from '../prismicio'
import { IPrimary } from '../slices/Song'
import styles from '../styles/Home.module.css'

interface IProps {
  songs: SliceZoneLike<SliceLike<string>>
}

const Home: FunctionComponent<IProps> = (props) => {
  const [currentSong, setCurrentSong] = useState({});
  const [playing, setPlaying] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Amofy</title>
        <link rel = "icon" href="assets/Safeimagekit-amongpng.png"
        type = "image/x-icon"></link>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <Playlist slices={props.songs} setSong={(data: IPrimary) => setCurrentSong(data) }/>
      {/* @ts-ignore */}
      <BottomBar songInfo={currentSong} changeNext={() => {}} changePrev={() => {}}/>


      
    </div>
  )
}

export const getServerSideProps = async () => {
  let notFound = false;
  let data;
  const client = createClient(); 

  try {
    data = await client.getByUID("playlist", "main");
  }
    catch (e){
      console.error("Playlist not found");
      notFound = true;
    }
    console.dir( data, { depth : null})
    return{
      props:{ songs: data?.data.slices},
      notFound: notFound
    }
  
}

export default Home