import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Playlist } from '../components/Playlist/Playlist'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Amofy</title>
        <link rel = "icon" href="assets/Safeimagekit-amongpng.png"
        type = "image/x-icon"></link>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <Playlist />


      
    </div>
  )
}

export default Home
